### ISSUE TITLE
Document the mongobackup docker image 

### ISSUE THREAD

**Issue by thinkh** [Caleydo/caleydo_data_mongo#16]
The [mongobackup](https://hub.docker.com/r/datavisyn/mongobackup) docker image creates a backup of mongodb running on a different host and stores the backup file on a persistent volume. A cron job can be set as environment variable to trigger the backup at specific times.

**Kubernetes configuration**

```yaml
spec:
  containers:
    - name: db-mongo
      image: mongo:3.2
      resources:
        limits:
          memory: 128Mi
        requests:
          memory: 64Mi
      volumeMounts:
        - name: local-data
          mountPath: /data/db
    - name: db-mongo-backup
      image: datavisyn/mongobackup:3.2
      volumeMounts:
        - name: persistent-data
          mountPath: /backup
          subPath: new_cluster
      command:
        - /bin/bash
        - /start.sh
        - restore-first
      env:
        - name: CRON_SCHEDULE
          value: "45 23 * * *"
        - name: MONGO_HOST
          value: localhost
  volumes:
    - name: persistent-data
      hostPath:
        #directory location on host
        path: /home/ubuntu/kubernetes/persistent-data
    - name: local-data
      hostPath:
        #directory location on host
        path: /home/ubuntu/kubernetes/local-data
```

The following scripts are available within the [mongobackup](https://hub.docker.com/r/datavisyn/mongobackup) image.

**entrypoint.sh**

```sh
#!/bin/bash
set -e

if [ "${1:0:1}" = '-' ]; then
        set -- mongod "$@"
fi

# allow the container to be started with `--user`
if [ "$1" = 'mongod' -a "$(id -u)" = '0' ]; then
        chown -R mongodb /data/configdb /data/db
        exec gosu mongodb "$BASH_SOURCE" "$@"
fi

if [ "$1" = 'mongod' ]; then
        numa='numactl --interleave=all'
        if $numa true &> /dev/null; then
                set -- $numa "$@"
        fi
fi

exec "$@"
```

**start.sh**

```sh
#!/bin/bash

set -e

if [[ "$1" == 'no-cron' ]]; then
    exec /backup.sh
else
    if [[ "$1" == 'restore-first' ]] && [[ -f ${MONGO_BACKUP_FILE} ]]; then
      echo restoring backup
      mongorestore --host ${MONGO_HOST} --gzip --archive=${MONGO_BACKUP_FILE}
    fi
    LOGFIFO='/var/log/cron.fifo'
    if [[ ! -e "$LOGFIFO" ]]; then
        mkfifo "$LOGFIFO"
    fi
    CRON_ENV="MONGO_HOST='$MONGO_HOST'"
    CRON_ENV="$CRON_ENV\nMONGO_BACKUP_FILE='$MONGO_BACKUP_FILE'"
    echo -e "$CRON_SCHEDULE /backup.sh > $LOGFIFO 2>&1"
    echo -e "$CRON_ENV\n$CRON_SCHEDULE /backup.sh > $LOGFIFO 2>&1" | crontab
    crontab -l
    cron
    tail -f "$LOGFIFO"
fi
```

**backup.sh**

```sh
#!/bin/bash

set -e

echo "Job started: $(date)"

echo mongodump --host ${MONGO_HOST} --gzip --archive=$MONGO_BACKUP_FILE
mongodump --host ${MONGO_HOST} --gzip --archive=$MONGO_BACKUP_FILE

echo "Job finished: $(date)"
```
